//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeneralDepartmentOfLawAffairs {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class LetterSentences {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LetterSentences() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GeneralDepartmentOfLawAffairs.LetterSentences", typeof(LetterSentences).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بشأن ....... .
        /// </summary>
        public static string about {
            get {
                return ResourceManager.GetString("about", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to النيابة الإدارية .
        /// </summary>
        public static string AdministrativeProsecution {
            get {
                return ResourceManager.GetString("AdministrativeProsecution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to السيد الأستاذ المستشار/.
        /// </summary>
        public static string Advisor {
            get {
                return ResourceManager.GetString("Advisor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نائب رئيس هيئة النيابة الإدارية.
        /// </summary>
        public static string Advisor2 {
            get {
                return ResourceManager.GetString("Advisor2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ومدير .
        /// </summary>
        public static string Advisor3 {
            get {
                return ResourceManager.GetString("Advisor3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قطاع الشئون.
        /// </summary>
        public static string AffairsSector {
            get {
                return ResourceManager.GetString("AffairsSector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المطلوب.
        /// </summary>
        public static string Agreement {
            get {
                return ResourceManager.GetString("Agreement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to التضامن الاجتماعي بالإسكندرية.
        /// </summary>
        public static string Alexandria {
            get {
                return ResourceManager.GetString("Alexandria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إلحاقا لكتابنا رقم .
        /// </summary>
        public static string append {
            get {
                return ResourceManager.GetString("append", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برجاء بعد الاطلاع التفضل بالتنبيه باتخاذ اللازم نحو التحقيق في الواقعة وموافاتنا برقم القيد القضائي ونتيجة التحقيق حتى يتسنى لنا اتخاذ اللازم..
        /// </summary>
        public static string ApRefRequest {
            get {
                return ResourceManager.GetString("ApRefRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جمهورية مصر العربية.
        /// </summary>
        public static string arabRepublicOfEgypt {
            get {
                return ResourceManager.GetString("arabRepublicOfEgypt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to التضامن الاجتماعي بأسيوط.
        /// </summary>
        public static string Asiut {
            get {
                return ResourceManager.GetString("Asiut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to التضامن الاجتماعي بأسوان.
        /// </summary>
        public static string Aswan {
            get {
                return ResourceManager.GetString("Aswan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مرفقات :.
        /// </summary>
        public static string Attachments {
            get {
                return ResourceManager.GetString("Attachments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to التضامن الاجتماعي ببني سويف.
        /// </summary>
        public static string BanySwaif {
            get {
                return ResourceManager.GetString("BanySwaif", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to التضامن الاجتماعي بالبحيرة.
        /// </summary>
        public static string Behera {
            get {
                return ResourceManager.GetString("Behera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to التضامن الاجتماعي بالقاهرة.
        /// </summary>
        public static string Cairo {
            get {
                return ResourceManager.GetString("Cairo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رئيس الادارة المركزية لشئون مكتب الوزير.
        /// </summary>
        public static string CCDepartment {
            get {
                return ResourceManager.GetString("CCDepartment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مدير إدارة التحقيقات.
        /// </summary>
        public static string CDepartment {
            get {
                return ResourceManager.GetString("CDepartment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الادارة المركزية للحماية الاجتماعية.
        /// </summary>
        public static string CDept1 {
            get {
                return ResourceManager.GetString("CDept1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الادارة المركزية للتنمية الاجتماعية.
        /// </summary>
        public static string CDept2 {
            get {
                return ResourceManager.GetString("CDept2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الادارة المركزية للرعاية الاجتماعية.
        /// </summary>
        public static string CDept3 {
            get {
                return ResourceManager.GetString("CDept3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الادارة المركزية للجمعيات والاتحادات.
        /// </summary>
        public static string CDept4 {
            get {
                return ResourceManager.GetString("CDept4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الادارة المركزية للشئون المالية والادارية.
        /// </summary>
        public static string CDept5 {
            get {
                return ResourceManager.GetString("CDept5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الادارة المركزية للتنمية البشرية.
        /// </summary>
        public static string CDept6 {
            get {
                return ResourceManager.GetString("CDept6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الادارة المركزية لشئون المديريات.
        /// </summary>
        public static string CDept7 {
            get {
                return ResourceManager.GetString("CDept7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إنقطاع.
        /// </summary>
        public static string Cease {
            get {
                return ResourceManager.GetString("Cease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to في التحقيق رقم.
        /// </summary>
        public static string CeaseNote1 {
            get {
                return ResourceManager.GetString("CeaseNote1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to وحيث أن هذا التصرف من جانبه يعد إخلالا بواجباته الوظيفية مما يشكل في حقه ذنباً إدارياً يستوجب مؤاخذته عليه تأديبياً طبقاً لنص المواد 46، 58، 61، 62 من قانون الخدمة المدنية الصادر بالقانون رقم 81 لسنة 2016..
        /// </summary>
        public static string CeaseNote10 {
            get {
                return ResourceManager.GetString("CeaseNote10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لذلك وتأسيساً على ما تقدم:.
        /// </summary>
        public static string CeaseNote11 {
            get {
                return ResourceManager.GetString("CeaseNote11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تتشرف الإدارة بإحالة الأوراق إلي السيد الأستاذ.
        /// </summary>
        public static string CeaseNote12 {
            get {
                return ResourceManager.GetString("CeaseNote12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لاتخاذ اللازم نحو.
        /// </summary>
        public static string CeaseNote13 {
            get {
                return ResourceManager.GetString("CeaseNote13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  قيد الواقعة مخالفة إدارية طبقاً لنص للمواد 46، 58، 61، 62 من قانون الخدمة المدنية الصادر بالقانون رقم 81 لسنة 2016.
        /// </summary>
        public static string CeaseNote14 {
            get {
                return ResourceManager.GetString("CeaseNote14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ضد.
        /// </summary>
        public static string CeaseNote15 {
            get {
                return ResourceManager.GetString("CeaseNote15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لأنه في غضون.
        /// </summary>
        public static string CeaseNote16 {
            get {
                return ResourceManager.GetString("CeaseNote16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بوصفه السابق وبدائرة عمله المشار اليها.
        /// </summary>
        public static string CeaseNote17 {
            get {
                return ResourceManager.GetString("CeaseNote17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to على النحو الوارد تفصيلا بالتحقيق..
        /// </summary>
        public static string CeaseNote18 {
            get {
                return ResourceManager.GetString("CeaseNote18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  مجازاة المذكور إداريا لما نسب إليه..
        /// </summary>
        public static string CeaseNote19 {
            get {
                return ResourceManager.GetString("CeaseNote19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to توجز الواقعة فيما تضمنه كتاب.
        /// </summary>
        public static string CeaseNote2 {
            get {
                return ResourceManager.GetString("CeaseNote2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  احتساب.
        /// </summary>
        public static string CeaseNote20 {
            get {
                return ResourceManager.GetString("CeaseNote20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to انقطاع عن العمل بدون إذن وبدون أجر..
        /// </summary>
        public static string CeaseNote21 {
            get {
                return ResourceManager.GetString("CeaseNote21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to التوصية بأعمال ما جاء بلائحة الجزاءات الصادرة بالقرار الوزاري رقم 252/96 في بندها الأول الخاص بمواعيد العمل الرسمية المخالفة رقم (3) والتي حددت الحد الأدنى للانقطاع عن العمل بدون إذن أو عذر مقبول بالإنذار والحد الأقصى بخصم عشرة أيام من الراتب..
        /// </summary>
        public static string CeaseNote22 {
            get {
                return ResourceManager.GetString("CeaseNote22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to من العاملين ب.
        /// </summary>
        public static string CeaseNote23 {
            get {
                return ResourceManager.GetString("CeaseNote23", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عما هو منسوب اليه من.
        /// </summary>
        public static string CeaseNote24 {
            get {
                return ResourceManager.GetString("CeaseNote24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to وحيث ان هذه المخالفة ثابتة في حقه من واقع اعترافه شخصيا بذلك ولا وجه لما تعلل به من أسباب لم يعززها بدليل يساندها..
        /// </summary>
        public static string CeaseNote25 {
            get {
                return ResourceManager.GetString("CeaseNote25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to انقطع عن العمل .
        /// </summary>
        public static string CeaseNote26 {
            get {
                return ResourceManager.GetString("CeaseNote26", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to وما ارفق به من أوراق والمحال الى هذه الإدارة للتحقيق في.
        /// </summary>
        public static string CeaseNote3 {
            get {
                return ResourceManager.GetString("CeaseNote3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to وبسؤال/.
        /// </summary>
        public static string CeaseNote4 {
            get {
                return ResourceManager.GetString("CeaseNote4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to وحيث أنه تم الاطلاع على المستندات الاتية:.
        /// </summary>
        public static string CeaseNote5 {
            get {
                return ResourceManager.GetString("CeaseNote5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to وحيث يبين من العرض السابق للواقعة أنه نسب إلى /.
        /// </summary>
        public static string CeaseNote6 {
            get {
                return ResourceManager.GetString("CeaseNote6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to انقطاعه عن العمل .
        /// </summary>
        public static string CeaseNote7 {
            get {
                return ResourceManager.GetString("CeaseNote7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بدون اذن.
        /// </summary>
        public static string CeaseNote8 {
            get {
                return ResourceManager.GetString("CeaseNote8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to علما بإن المذكور ليس لديه رصيد من الاجازات العارضة او الاعتيادية عن العام الحالي.
        /// </summary>
        public static string CeaseNote9 {
            get {
                return ResourceManager.GetString("CeaseNote9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الإدارة المركزية لشئون مكتب الوزير.
        /// </summary>
        public static string CentralDepartName {
            get {
                return ResourceManager.GetString("CentralDepartName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رئيس الادارة المركزية.
        /// </summary>
        public static string CM_Dept {
            get {
                return ResourceManager.GetString("CM_Dept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to والمشرف على شئون مكتب الوزير.
        /// </summary>
        public static string CM_Dept_adj {
            get {
                return ResourceManager.GetString("CM_Dept_adj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لشئون مكتب الوزير.
        /// </summary>
        public static string CM_Dept_comp {
            get {
                return ResourceManager.GetString("CM_Dept_comp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to التضامن الاجتماعي بالدقهلية.
        /// </summary>
        public static string Daqahleya {
            get {
                return ResourceManager.GetString("Daqahleya", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بتاريخ.
        /// </summary>
        public static string Dated {
            get {
                return ResourceManager.GetString("Dated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المؤرخ .
        /// </summary>
        public static string Dated_1 {
            get {
                return ResourceManager.GetString("Dated_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إدارة التحقيقات.
        /// </summary>
        public static string DepartmentName {
            get {
                return ResourceManager.GetString("DepartmentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 19 شارع المراغي - العجوزة .
        /// </summary>
        public static string DeptAddress {
            get {
                return ResourceManager.GetString("DeptAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المحقق.
        /// </summary>
        public static string detective {
            get {
                return ResourceManager.GetString("detective", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هل تريد الاستمرار؟.
        /// </summary>
        public static string doContinue {
            get {
                return ResourceManager.GetString("doContinue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قرار.
        /// </summary>
        public static string DraftResolution1 {
            get {
                return ResourceManager.GetString("DraftResolution1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to وبناءً على ما عرضه علينا السيد الأستاذ / مدير عام.
        /// </summary>
        public static string DraftResolution10 {
            get {
                return ResourceManager.GetString("DraftResolution10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قررنا.
        /// </summary>
        public static string DraftResolution11 {
            get {
                return ResourceManager.GetString("DraftResolution11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المادة الأولى.
        /// </summary>
        public static string DraftResolution12 {
            get {
                return ResourceManager.GetString("DraftResolution12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المادة الثانية.
        /// </summary>
        public static string DraftResolution13 {
            get {
                return ResourceManager.GetString("DraftResolution13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المادة الثالثة.
        /// </summary>
        public static string DraftResolution14 {
            get {
                return ResourceManager.GetString("DraftResolution14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المادة الرابعة.
        /// </summary>
        public static string DraftResolution15 {
            get {
                return ResourceManager.GetString("DraftResolution15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المادة الخامسة.
        /// </summary>
        public static string DraftResolution16 {
            get {
                return ResourceManager.GetString("DraftResolution16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المادة السادسة.
        /// </summary>
        public static string DraftResolution17 {
            get {
                return ResourceManager.GetString("DraftResolution17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المادة السابعة.
        /// </summary>
        public static string DraftResolution18 {
            get {
                return ResourceManager.GetString("DraftResolution18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المادة الثامنة.
        /// </summary>
        public static string DraftResolution19 {
            get {
                return ResourceManager.GetString("DraftResolution19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بعد الاطلاع على قانون الخدمة المدنية الصادر بالقانون رقم 81 لسنة 2016 ولائحته التنفيذية..
        /// </summary>
        public static string DraftResolution2 {
            get {
                return ResourceManager.GetString("DraftResolution2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المادة التاسعة.
        /// </summary>
        public static string DraftResolution20 {
            get {
                return ResourceManager.GetString("DraftResolution20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المادة العاشرة.
        /// </summary>
        public static string DraftResolution21 {
            get {
                return ResourceManager.GetString("DraftResolution21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to على جميع الجهات المختصة تنفيذ هذا القرار كل فيما يخصه..
        /// </summary>
        public static string DraftResolution22 {
            get {
                return ResourceManager.GetString("DraftResolution22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مجازاة المذكور إداريا لما نسب إليه بخصم          .
        /// </summary>
        public static string DraftResolution23 {
            get {
                return ResourceManager.GetString("DraftResolution23", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to من الراتب..
        /// </summary>
        public static string DraftResolution24 {
            get {
                return ResourceManager.GetString("DraftResolution24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to وعلى قرار رئيس الجمهورية.
        /// </summary>
        public static string DraftResolution3 {
            get {
                return ResourceManager.GetString("DraftResolution3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بشأن التشكيل الوزاري الحالي..
        /// </summary>
        public static string DraftResolution4 {
            get {
                return ResourceManager.GetString("DraftResolution4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to وعلى القرار الوزاري رقم 252 / 96 بشأن لائحة الجزاءات التأديبية للعاملين بديوان عام الوزارة..
        /// </summary>
        public static string DraftResolution5 {
            get {
                return ResourceManager.GetString("DraftResolution5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to وعلى كتاب.
        /// </summary>
        public static string DraftResolution6 {
            get {
                return ResourceManager.GetString("DraftResolution6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to والمرفق به مذكرة التحقيق الإداري.
        /// </summary>
        public static string DraftResolution7 {
            get {
                return ResourceManager.GetString("DraftResolution7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to والمقيد ضد /.
        /// </summary>
        public static string DraftResolution8 {
            get {
                return ResourceManager.GetString("DraftResolution8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to في الموضوع الموضح فيما بعد..
        /// </summary>
        public static string DraftResolution9 {
            get {
                return ResourceManager.GetString("DraftResolution9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تحريرا في:.
        /// </summary>
        public static string EditedIn {
            get {
                return ResourceManager.GetString("EditedIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to التضامن الاجتماعي بالوادي الجديد.
        /// </summary>
        public static string ElWadyElGadid {
            get {
                return ResourceManager.GetString("ElWadyElGadid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم الموظف:.
        /// </summary>
        public static string EmpName {
            get {
                return ResourceManager.GetString("EmpName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الحقول الاتية فارغة.
        /// </summary>
        public static string emptyFields {
            get {
                return ResourceManager.GetString("emptyFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to التضامن الاجتماعي بالفيوم.
        /// </summary>
        public static string Fayoum {
            get {
                return ResourceManager.GetString("Fayoum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خامسا: -.
        /// </summary>
        public static string Fifth {
            get {
                return ResourceManager.GetString("Fifth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اولاً: -.
        /// </summary>
        public static string First {
            get {
                return ResourceManager.GetString("First", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لسنة.
        /// </summary>
        public static string ForYear {
            get {
                return ResourceManager.GetString("ForYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رابعا: -.
        /// </summary>
        public static string Fourth {
            get {
                return ResourceManager.GetString("Fourth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الجمعة .
        /// </summary>
        public static string Friday {
            get {
                return ResourceManager.GetString("Friday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to من.
        /// </summary>
        public static string From {
            get {
                return ResourceManager.GetString("From", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الوقائع.
        /// </summary>
        public static string Gazzette {
            get {
                return ResourceManager.GetString("Gazzette", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الإدارة العامة للمكتب الفني.
        /// </summary>
        public static string GDept1 {
            get {
                return ResourceManager.GetString("GDept1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الإدارة العامة للتوثيق والمعلومات.
        /// </summary>
        public static string GDept10 {
            get {
                return ResourceManager.GetString("GDept10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الإدارة العامة للشئون الإدارية.
        /// </summary>
        public static string GDept11 {
            get {
                return ResourceManager.GetString("GDept11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الإدارة العامة للشئون المالية.
        /// </summary>
        public static string GDept12 {
            get {
                return ResourceManager.GetString("GDept12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الإدارة العامة للدفاع الاجتماعي.
        /// </summary>
        public static string GDept13 {
            get {
                return ResourceManager.GetString("GDept13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الإدارة العامة لشئون العاملين.
        /// </summary>
        public static string GDept14 {
            get {
                return ResourceManager.GetString("GDept14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الإدارة العامة للأسرة والطفولة.
        /// </summary>
        public static string GDept15 {
            get {
                return ResourceManager.GetString("GDept15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الإدارة العامة للأمن.
        /// </summary>
        public static string GDept16 {
            get {
                return ResourceManager.GetString("GDept16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الإدارة العامة للجمعيات.
        /// </summary>
        public static string GDept17 {
            get {
                return ResourceManager.GetString("GDept17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الإدارة العامة للإتحادات والمؤسسات.
        /// </summary>
        public static string GDept18 {
            get {
                return ResourceManager.GetString("GDept18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الإدارة العامة للمنظمات الأهلية والتعاونيات.
        /// </summary>
        public static string GDept19 {
            get {
                return ResourceManager.GetString("GDept19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الإدارة العامة للتدريب.
        /// </summary>
        public static string GDept2 {
            get {
                return ResourceManager.GetString("GDept2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الإدارة العامة لشئون المديريات - وجه بحري.
        /// </summary>
        public static string GDept20 {
            get {
                return ResourceManager.GetString("GDept20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الإدارة العامة لشئون المديريات - وجه قبلي.
        /// </summary>
        public static string GDept21 {
            get {
                return ResourceManager.GetString("GDept21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الإدارة العامة لشئون المديريات - القاهرة الكبرى.
        /// </summary>
        public static string GDept22 {
            get {
                return ResourceManager.GetString("GDept22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الإدارة العامة للتنظيم والإدارة.
        /// </summary>
        public static string GDept23 {
            get {
                return ResourceManager.GetString("GDept23", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الإدارة العامة للغلاقات العامة والإعلام.
        /// </summary>
        public static string GDept24 {
            get {
                return ResourceManager.GetString("GDept24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الإدارة العامة لخدمة المواطنين.
        /// </summary>
        public static string GDept25 {
            get {
                return ResourceManager.GetString("GDept25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الإدارة العامة لتأهيل المعاقين.
        /// </summary>
        public static string GDept26 {
            get {
                return ResourceManager.GetString("GDept26", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الإدارة العامة للخدمة العامة.
        /// </summary>
        public static string GDept27 {
            get {
                return ResourceManager.GetString("GDept27", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الإدارة العامة لشئون المرأة.
        /// </summary>
        public static string GDept28 {
            get {
                return ResourceManager.GetString("GDept28", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الإدارة العامة للأندية.
        /// </summary>
        public static string GDept29 {
            get {
                return ResourceManager.GetString("GDept29", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الإدارة العامة للإتصالات السياسية.
        /// </summary>
        public static string GDept3 {
            get {
                return ResourceManager.GetString("GDept3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الإدارة العامة للمتابعة.
        /// </summary>
        public static string GDept30 {
            get {
                return ResourceManager.GetString("GDept30", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الإدارة العامة للغلاقات الخارجية.
        /// </summary>
        public static string GDept31 {
            get {
                return ResourceManager.GetString("GDept31", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الإدارة العامة للضمان الاجتماعي والتعويضات.
        /// </summary>
        public static string GDept32 {
            get {
                return ResourceManager.GetString("GDept32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الإدارة العامة للأزمات والإغاثة.
        /// </summary>
        public static string GDept33 {
            get {
                return ResourceManager.GetString("GDept33", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الإدارة العامة للإعداد الفني والتوجيه.
        /// </summary>
        public static string GDept4 {
            get {
                return ResourceManager.GetString("GDept4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الإدارة العامة للتسويق والمعارض.
        /// </summary>
        public static string GDept5 {
            get {
                return ResourceManager.GetString("GDept5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الإدارة العامة للتكوين المهني والصناعات الصغيرة.
        /// </summary>
        public static string GDept6 {
            get {
                return ResourceManager.GetString("GDept6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الإدارة العامة لتنمية المجتمعات المحلية.
        /// </summary>
        public static string GDept7 {
            get {
                return ResourceManager.GetString("GDept7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الإدارة العامة للشئون الهندسية.
        /// </summary>
        public static string GDept8 {
            get {
                return ResourceManager.GetString("GDept8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الإدارة العامة للمجتمعات العمرانية الجديدة.
        /// </summary>
        public static string GDept9 {
            get {
                return ResourceManager.GetString("GDept9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الإدارة العامة للشئون القانونية.
        /// </summary>
        public static string GeneralDepartName {
            get {
                return ResourceManager.GetString("GeneralDepartName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برجاء بعد الاطلاع التفضل بالتنبيه باتخاذ اللازم..
        /// </summary>
        public static string GeneralLetter {
            get {
                return ResourceManager.GetString("GeneralLetter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المدير العام.
        /// </summary>
        public static string GeneralManager {
            get {
                return ResourceManager.GetString("GeneralManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برجاء بعد الاطلاع التفضل بالتنبيه باتخاذ اللازم نحو.
        /// </summary>
        public static string GeneralRequest {
            get {
                return ResourceManager.GetString("GeneralRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to التضامن الاجتماعي بالغربية.
        /// </summary>
        public static string Gharbeya {
            get {
                return ResourceManager.GetString("Gharbeya", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to التضامن الاجتماعي بالجيزة.
        /// </summary>
        public static string Giza {
            get {
                return ResourceManager.GetString("Giza", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مدير عام .
        /// </summary>
        public static string GM_Dept {
            get {
                return ResourceManager.GetString("GM_Dept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تحية طيبة .... وبعد.
        /// </summary>
        public static string greet {
            get {
                return ResourceManager.GetString("greet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to وتفضلوا بقبول فائق الاحترام،.
        /// </summary>
        public static string Greeting {
            get {
                return ResourceManager.GetString("Greeting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رئيس .
        /// </summary>
        public static string Head {
            get {
                return ResourceManager.GetString("Head", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قطاع الشئون المالية والادارية والتنمية البشرية وشئون المديريات.
        /// </summary>
        public static string HGC {
            get {
                return ResourceManager.GetString("HGC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to التاريخ .
        /// </summary>
        public static string History {
            get {
                return ResourceManager.GetString("History", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نرسل لسيادتكم مرافقاً لكتابنا هذا ملف وأوراق الفحص رقم.
        /// </summary>
        public static string InspctionRefererring1 {
            get {
                return ResourceManager.GetString("InspctionRefererring1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to والمؤشر على مذكرته من معالي الوزيرة بالإحالة للنيابة الإدارية..
        /// </summary>
        public static string InspctionRefererring2 {
            get {
                return ResourceManager.GetString("InspctionRefererring2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برجاء بعد الاطلاع التفضل باتخاذ اللازم نحو التحقيق في الشكوى محل الفحص وموافاتنا بتاريخ ورقم القيد القضائي ونتيجة التحقيق حتى يتسنى لنا اتخاذ اللازم..
        /// </summary>
        public static string InspctionRefererring3 {
            get {
                return ResourceManager.GetString("InspctionRefererring3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ملف الفحص رقم .
        /// </summary>
        public static string InspctionRefererring4 {
            get {
                return ResourceManager.GetString("InspctionRefererring4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فحص.
        /// </summary>
        public static string Inspection {
            get {
                return ResourceManager.GetString("Inspection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برجاء بعد الاطلاع التفضل بالتنبيه باتخاذ اللازم نحو فحص الشكوى المشار إليها وموافاتنا بنتيجة الفحص مدعمة بالمستندات حتى يتسنى لنا اتخاذ اللازم..
        /// </summary>
        public static string inspectionRequest {
            get {
                return ResourceManager.GetString("inspectionRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بشأن طلب حضور السيد/ .
        /// </summary>
        public static string intensive {
            get {
                return ResourceManager.GetString("intensive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برجاء التفضل بالتنبيه مشددا على المذكور بضرورة الحضور لمقر إدارة التحقيقات بالعنوان أعلاه في العاشرة صباح يوم .
        /// </summary>
        public static string intensive_1 {
            get {
                return ResourceManager.GetString("intensive_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ويخطر بأنه في حالة عدم حضوره سيعتبر متنازلا عن حقه في الدفاع عن نفسه..
        /// </summary>
        public static string intensive_2 {
            get {
                return ResourceManager.GetString("intensive_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تحقيق.
        /// </summary>
        public static string Investigation {
            get {
                return ResourceManager.GetString("Investigation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نرسل لسيادتكم مرافقاً لكتابنا هذا ملف وأوراق التحقيق رقم.
        /// </summary>
        public static string InvestigationRefererring1 {
            get {
                return ResourceManager.GetString("InvestigationRefererring1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to والمؤشر على مذكرته من معالي الوزيرة بالإحالة للنيابة الإدارية..
        /// </summary>
        public static string InvestigationRefererring2 {
            get {
                return ResourceManager.GetString("InvestigationRefererring2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برجاء بعد الاطلاع التفضل باتخاذ اللازم نحو التحقيق في الواقعة وموافاتنا بتاريخ ورقم القيد القضائي ونتيجة التحقيق حتى يتسنى لنا اتخاذ اللازم..
        /// </summary>
        public static string InvestigationRefererring3 {
            get {
                return ResourceManager.GetString("InvestigationRefererring3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ملف التحقيق رقم .
        /// </summary>
        public static string InvestigationRefererring4 {
            get {
                return ResourceManager.GetString("InvestigationRefererring4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تحقيق رقم .
        /// </summary>
        public static string InvNo {
            get {
                return ResourceManager.GetString("InvNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to التضامن الاجتماعي بالإسماعيلية.
        /// </summary>
        public static string Ismaeileya {
            get {
                return ResourceManager.GetString("Ismaeileya", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إيماءً إلى كتاب هيئة النيابة الإدارية .
        /// </summary>
        public static string IssuanceRescript1 {
            get {
                return ResourceManager.GetString("IssuanceRescript1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to والمرفق به قرار لجنة التأديب رقم .
        /// </summary>
        public static string IssuanceRescript2 {
            get {
                return ResourceManager.GetString("IssuanceRescript2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to والصادر بنتيجة التصرف في القضية رقم .
        /// </summary>
        public static string IssuanceRescript3 {
            get {
                return ResourceManager.GetString("IssuanceRescript3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نرسل مرافقاً لكتابنا هذا مشروع القرار التنفيذي طبقاً لما انتهى إليه رأي النيابة الإدارية في القضية المشار إليها..
        /// </summary>
        public static string IssuanceRescript4 {
            get {
                return ResourceManager.GetString("IssuanceRescript4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برجاء بعد الاطلاع التفضل بالتنبيه باتخاذ اللازم نحو استصدار قرار تنفيذي بنتيجة التصرف في القضية المشار إليها طبقا لمشروع القرار المرفق مشفوعا بتوقيع المخالف بالاسم الثلاثي بما يفيد العلم بهذا القرار وتاريخه وذلك طبقاً لطلب النيابة..
        /// </summary>
        public static string IssuanceRescript5 {
            get {
                return ResourceManager.GetString("IssuanceRescript5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المسطر بعالية صورة ما أرسل إلى الإدارة وذلك بالإشارة إلى كتابكم رقم .
        /// </summary>
        public static string IssuanceRescript6 {
            get {
                return ResourceManager.GetString("IssuanceRescript6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to وسوف نوافيكم بالمطلوب فور وروده إلينا..
        /// </summary>
        public static string IssuanceRescript7 {
            get {
                return ResourceManager.GetString("IssuanceRescript7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to التضامن الاجتماعي بكفر الشيخ.
        /// </summary>
        public static string KafrElSheikh {
            get {
                return ResourceManager.GetString("KafrElSheikh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب كتابة أو اختيار رقم التحقيق.
        /// </summary>
        public static string LblMessage {
            get {
                return ResourceManager.GetString("LblMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب كتابة الموضوع بشكل واضح.
        /// </summary>
        public static string LblMessage_1 {
            get {
                return ResourceManager.GetString("LblMessage_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب كتابة او اختيار رقم الفحص.
        /// </summary>
        public static string LblMessage_10 {
            get {
                return ResourceManager.GetString("LblMessage_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب ملء الحقول الخالية .
        /// </summary>
        public static string LblMessage_11 {
            get {
                return ResourceManager.GetString("LblMessage_11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب كتابة اسم المطلوب حضوره.
        /// </summary>
        public static string LblMessage_2 {
            get {
                return ResourceManager.GetString("LblMessage_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم تحديد موعد الجلسة بتاريخ سابق.
        /// </summary>
        public static string LblMessage_3 {
            get {
                return ResourceManager.GetString("LblMessage_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سيتم تحديد موعد الجلسة بتاريخ اليوم.
        /// </summary>
        public static string LblMessage_4 {
            get {
                return ResourceManager.GetString("LblMessage_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب تحديد تاريخ الإحالة بشكل صحيح.
        /// </summary>
        public static string LblMessage_5 {
            get {
                return ResourceManager.GetString("LblMessage_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب كتابة رقم الصادر لاخر اخطار.
        /// </summary>
        public static string LblMessage_6 {
            get {
                return ResourceManager.GetString("LblMessage_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب تحديد تاريخ الصادر بشكل صحيح.
        /// </summary>
        public static string LblMessage_7 {
            get {
                return ResourceManager.GetString("LblMessage_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب ملء الحقول الخالية والتأكد من صحة التواريخ.
        /// </summary>
        public static string LblMessage_8 {
            get {
                return ResourceManager.GetString("LblMessage_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب كتابة او اختيار رقم التحقيق.
        /// </summary>
        public static string LblMessage_9 {
            get {
                return ResourceManager.GetString("LblMessage_9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to التضامن الاجتماعي بالأقصر.
        /// </summary>
        public static string Luxor {
            get {
                return ResourceManager.GetString("Luxor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to التضامن الاجتماعي بمرسى مطروح.
        /// </summary>
        public static string MarsaMatrouh {
            get {
                return ResourceManager.GetString("MarsaMatrouh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to التضامن الاجتماعي بالمنيا.
        /// </summary>
        public static string Menya {
            get {
                return ResourceManager.GetString("Menya", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to وزير التضامن الاجتماعي.
        /// </summary>
        public static string Minister {
            get {
                return ResourceManager.GetString("Minister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to وزارة التضامن الاجتماعي.
        /// </summary>
        public static string MinistryMame {
            get {
                return ResourceManager.GetString("MinistryMame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تكليف بمأمورية.
        /// </summary>
        public static string Mission {
            get {
                return ResourceManager.GetString("Mission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الوظيفة:.
        /// </summary>
        public static string Mission1 {
            get {
                return ResourceManager.GetString("Mission1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المستوى الوظيفي:.
        /// </summary>
        public static string Mission2 {
            get {
                return ResourceManager.GetString("Mission2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الإدارة التابع لها الموظف:.
        /// </summary>
        public static string Mission3 {
            get {
                return ResourceManager.GetString("Mission3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جهة تنفيذ المأمورية:.
        /// </summary>
        public static string Mission4 {
            get {
                return ResourceManager.GetString("Mission4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عنوان جهة المأمورية:.
        /// </summary>
        public static string Mission5 {
            get {
                return ResourceManager.GetString("Mission5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الغرض من المأمورية:.
        /// </summary>
        public static string Mission6 {
            get {
                return ResourceManager.GetString("Mission6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مدة المأمورية:.
        /// </summary>
        public static string Mission7 {
            get {
                return ResourceManager.GetString("Mission7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الاثنين .
        /// </summary>
        public static string Monday {
            get {
                return ResourceManager.GetString("Monday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to التضامن الاجتماعي بالمنوفية.
        /// </summary>
        public static string Monofeya {
            get {
                return ResourceManager.GetString("Monofeya", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to السيد الاستاذ/.
        /// </summary>
        public static string MR {
            get {
                return ResourceManager.GetString("MR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to السيدة الاستاذة/.
        /// </summary>
        public static string MRS {
            get {
                return ResourceManager.GetString("MRS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to والمتضمن طلب ترشيح أحد أعضاء الإدارة للاشتراك في اعمال اللجنة المزمع تشكيلها..
        /// </summary>
        public static string NominationLetter1 {
            get {
                return ResourceManager.GetString("NominationLetter1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نحيط علم سيادتكم بأن الإدارة قد رشحت الأستاذ/.
        /// </summary>
        public static string NominationLetter2 {
            get {
                return ResourceManager.GetString("NominationLetter2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الباحث القانوني بالإدارة للاشتراك في اعمال تلك اللجنة..
        /// </summary>
        public static string NominationLetter3 {
            get {
                return ResourceManager.GetString("NominationLetter3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برجاء بعد الاطلاع التفضل بالتنبيه باتخاذ اللازم نحو موافاتنا بصورة من قرار تشكيل اللجنة المشار اليها حتى يتسنى لنا اتخاذ اللازم..
        /// </summary>
        public static string NominationLetter4 {
            get {
                return ResourceManager.GetString("NominationLetter4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to التضامن الاجتماعي بشمال سيناء.
        /// </summary>
        public static string NorthSinai {
            get {
                return ResourceManager.GetString("NorthSinai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مذكرة.
        /// </summary>
        public static string Note {
            get {
                return ResourceManager.GetString("Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم.
        /// </summary>
        public static string Num {
            get {
                return ResourceManager.GetString("Num", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الرأي.
        /// </summary>
        public static string Openion {
            get {
                return ResourceManager.GetString("Openion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هيئة.
        /// </summary>
        public static string Organisation {
            get {
                return ResourceManager.GetString("Organisation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to صادر .
        /// </summary>
        public static string OutCome {
            get {
                return ResourceManager.GetString("OutCome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to التضامن الاجتماعي ببور سعيد.
        /// </summary>
        public static string PortSaid {
            get {
                return ResourceManager.GetString("PortSaid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الاجراء والنتيجة.
        /// </summary>
        public static string ProcAndResult {
            get {
                return ResourceManager.GetString("ProcAndResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to التضامن الاجتماعي بالقليوبية.
        /// </summary>
        public static string Qalyobeya {
            get {
                return ResourceManager.GetString("Qalyobeya", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to التضامن الاجتماعي بقنا.
        /// </summary>
        public static string Quena {
            get {
                return ResourceManager.GetString("Quena", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to التضامن الاجتماعي بالبحر الأحمر.
        /// </summary>
        public static string RedSea {
            get {
                return ResourceManager.GetString("RedSea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مدير مديرية .
        /// </summary>
        public static string RegonalManaget {
            get {
                return ResourceManager.GetString("RegonalManaget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بالإشارة إلى كتابكم رقم .
        /// </summary>
        public static string RescriptSent1 {
            get {
                return ResourceManager.GetString("RescriptSent1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to والمرفق به قرار لجنة التأديب رقم .
        /// </summary>
        public static string RescriptSent2 {
            get {
                return ResourceManager.GetString("RescriptSent2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بشأن القضية رقم .
        /// </summary>
        public static string RescriptSent3 {
            get {
                return ResourceManager.GetString("RescriptSent3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to والمقيدة ضد / .
        /// </summary>
        public static string RescriptSent4 {
            get {
                return ResourceManager.GetString("RescriptSent4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نرسل مرافقاً لكتابنا هذا صورة ضوئية من القرار رقم .
        /// </summary>
        public static string RescriptSent5 {
            get {
                return ResourceManager.GetString("RescriptSent5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to والصادر بنتيجة التصرف في القضية المشار اليها موقعا عليه ثلاثيا من المخالف بما يفيد العلم..
        /// </summary>
        public static string RescriptSent6 {
            get {
                return ResourceManager.GetString("RescriptSent6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برجاء بعد الاطلاع التفضل بالعلم والاحاطة واتخاذ اللازم..
        /// </summary>
        public static string RescriptSent7 {
            get {
                return ResourceManager.GetString("RescriptSent7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الباحث القانوني.
        /// </summary>
        public static string Researcher {
            get {
                return ResourceManager.GetString("Researcher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إستعجال في ال.
        /// </summary>
        public static string Rush {
            get {
                return ResourceManager.GetString("Rush", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to السبت .
        /// </summary>
        public static string Saturday {
            get {
                return ResourceManager.GetString("Saturday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ثانيا: -.
        /// </summary>
        public static string Second {
            get {
                return ResourceManager.GetString("Second", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برجاء بعد الاطلاع التفضل بالعلم والإحاطة..
        /// </summary>
        public static string sentCopyText {
            get {
                return ResourceManager.GetString("sentCopyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to صورة مرسلة إلى .
        /// </summary>
        public static string sentPhotoCopyTo {
            get {
                return ResourceManager.GetString("sentPhotoCopyTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سابعا: -.
        /// </summary>
        public static string Seventh {
            get {
                return ResourceManager.GetString("Seventh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to التضامن الاجتماعي بالشرقية.
        /// </summary>
        public static string Sharqeya {
            get {
                return ResourceManager.GetString("Sharqeya", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سادسا: -.
        /// </summary>
        public static string Sixth {
            get {
                return ResourceManager.GetString("Sixth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to التضامن الاجتماعي بسوهاج.
        /// </summary>
        public static string Sohag {
            get {
                return ResourceManager.GetString("Sohag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to التضامن الاجتماعي بجنوب سيناء.
        /// </summary>
        public static string SouthSinai {
            get {
                return ResourceManager.GetString("SouthSinai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برجاء التنبيه بالحضور على:.
        /// </summary>
        public static string Stimulation {
            get {
                return ResourceManager.GetString("Stimulation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بالحضور لمقر إدارة التحقيقات بالعنوان أعلاه في العاشرة صباح يوم .
        /// </summary>
        public static string StimulationSummon {
            get {
                return ResourceManager.GetString("StimulationSummon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لسماع أقواله في التحقيق رقم .
        /// </summary>
        public static string StimulationSummon_2 {
            get {
                return ResourceManager.GetString("StimulationSummon_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أمام الأستاذ/.
        /// </summary>
        public static string StimulationSummon_3 {
            get {
                return ResourceManager.GetString("StimulationSummon_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  المحقق بالإدارة.
        /// </summary>
        public static string StimulationSummon_4 {
            get {
                return ResourceManager.GetString("StimulationSummon_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الموضوع.
        /// </summary>
        public static string Subject {
            get {
                return ResourceManager.GetString("Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تكليف حضور.
        /// </summary>
        public static string Summon {
            get {
                return ResourceManager.GetString("Summon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الاحد .
        /// </summary>
        public static string Sunday {
            get {
                return ResourceManager.GetString("Sunday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to التضامن الاجتماعي بالسويس.
        /// </summary>
        public static string Swez {
            get {
                return ResourceManager.GetString("Swez", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مذكرة للعرض.
        /// </summary>
        public static string TableNote1 {
            get {
                return ResourceManager.GetString("TableNote1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تفضل معاليكم بالموافقة علي.
        /// </summary>
        public static string TableNote2 {
            get {
                return ResourceManager.GetString("TableNote2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تفضل سيادتكم بالموافقة علي.
        /// </summary>
        public static string TableNote3 {
            get {
                return ResourceManager.GetString("TableNote3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to وتفضلوا معاليكم بقبول وافر التحية والتقدير...
        /// </summary>
        public static string TableNote4 {
            get {
                return ResourceManager.GetString("TableNote4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to وتفضلوا سيادتكم بقبول وافر التحية والتقدير...
        /// </summary>
        public static string TableNote5 {
            get {
                return ResourceManager.GetString("TableNote5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مع الشكر.
        /// </summary>
        public static string Thanks {
            get {
                return ResourceManager.GetString("Thanks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شاكرين لسيادتكم حسن تعاونكم معنا.
        /// </summary>
        public static string ThankYou {
            get {
                return ResourceManager.GetString("ThankYou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ثالثا: -.
        /// </summary>
        public static string Third {
            get {
                return ResourceManager.GetString("Third", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الخميس .
        /// </summary>
        public static string Thursday {
            get {
                return ResourceManager.GetString("Thursday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إلى.
        /// </summary>
        public static string To {
            get {
                return ResourceManager.GetString("To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الثلاثاء .
        /// </summary>
        public static string Tuesday {
            get {
                return ResourceManager.GetString("Tuesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الاربعاء .
        /// </summary>
        public static string Wednesday {
            get {
                return ResourceManager.GetString("Wednesday", resourceCulture);
            }
        }
    }
}
