//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeneralDepartmentOfLawAffairs.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.9.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("أ./سمية عبد السلام")]
        public string GMName {
            get {
                return ((string)(this["GMName"]));
            }
            set {
                this["GMName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("محمد عثمان ابو المجد")]
        public string CMName {
            get {
                return ((string)(this["CMName"]));
            }
            set {
                this["CMName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("اسلام معروف")]
        public string ResearcherName {
            get {
                return ((string)(this["ResearcherName"]));
            }
            set {
                this["ResearcherName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(" أ./رقية عبد الغفور")]
        public string ChDeptName {
            get {
                return ((string)(this["ChDeptName"]));
            }
            set {
                this["ChDeptName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("**إسلام**")]
        public string researcherSign {
            get {
                return ((string)(this["researcherSign"]));
            }
            set {
                this["researcherSign"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("غادة فتحي والي")]
        public string MinisterName {
            get {
                return ((string)(this["MinisterName"]));
            }
            set {
                this["MinisterName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Blue")]
        public string CurrentSkinName {
            get {
                return ((string)(this["CurrentSkinName"]));
            }
            set {
                this["CurrentSkinName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("الإدارة العامة للشئون القانونية – إدارة التحقيقات")]
        public string DepartmentName {
            get {
                return ((string)(this["DepartmentName"]));
            }
            set {
                this["DepartmentName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("الثاني")]
        public string JobRank {
            get {
                return ((string)(this["JobRank"]));
            }
            set {
                this["JobRank"] = value;
            }
        }
    }
}
